CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(50) NOT NULL,
                       description VARCHAR(255),
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT pk_roles PRIMARY KEY (id),
                       CONSTRAINT uk_roles_name UNIQUE (name),
                       CONSTRAINT chk_roles_name_not_blank
                           CHECK (LENGTH(TRIM(name)) > 0)
);


CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           username VARCHAR(50) NOT NULL,
                           password_hash VARCHAR(255) NOT NULL,
                           first_name VARCHAR(100) NOT NULL,
                           last_name VARCHAR(100) NOT NULL,
                           email VARCHAR(254) NOT NULL,
                           active BOOLEAN NOT NULL DEFAULT TRUE,
                           created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT pk_app_users PRIMARY KEY (id),

                           CONSTRAINT uk_app_users_username
                               UNIQUE (username),

                           CONSTRAINT uk_app_users_email
                               UNIQUE (email),

                           CONSTRAINT chk_app_users_username_not_blank
                               CHECK (LENGTH(TRIM(username)) > 0),

                           CONSTRAINT chk_app_users_password_hash_not_blank
                               CHECK (LENGTH(TRIM(password_hash)) > 0),

                           CONSTRAINT chk_app_users_first_name_not_blank
                               CHECK (LENGTH(TRIM(first_name)) > 0),

                           CONSTRAINT chk_app_users_last_name_not_blank
                               CHECK (LENGTH(TRIM(last_name)) > 0),

                           CONSTRAINT chk_app_users_email_not_blank
                               CHECK (LENGTH(TRIM(email)) > 0)
);


CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT pk_user_roles
                                PRIMARY KEY (user_id, role_id),

                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES app_users (id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id)
                                    REFERENCES roles (id)
                                    ON DELETE RESTRICT
);


CREATE INDEX idx_user_roles_role_id
    ON user_roles (role_id);


INSERT INTO roles (name, description)
VALUES
    (
        'ADMIN',
        'Full system administration access'
    ),
    (
        'WAREHOUSE_MANAGER',
        'Warehouse management and approval access'
    ),
    (
        'WAREHOUSE_WORKER',
        'Daily warehouse operation access'
    );